project_id = "hynadwlwrscvjubryqlg"

[functions.run-start]
verify_jwt = false

[functions.run-step]
verify_jwt = false

[functions.run-abort]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false

[functions.notification-dispatcher]
verify_jwt = false

[functions.internal-job-trigger]
verify_jwt = false
